### ISSUE TITLE
Add a CLI argument that gets lyrics in a time interval

### ISSUE THREAD

**Issue by MohamedYasser97** [MohamedYasser97/lyricurator#11]
It should work like this `python lyricurator.py --interval 10`. This should print/tweet lyrics every 10 minutes.

**Comment by Kurtsley** [comment]
Hey, I've implemented this locally and would like permission to fork this repo.

**Comment by MohamedYasser97** [comment]
Sure, go ahead 👍 
Make sure to update the readme file with the new CLI argument `-i/--interval`
