### ISSUE TITLE
Add a CLI argument that gets a full song

### ISSUE THREAD

**Issue by MohamedYasser97** [MohamedYasser97/lyricurator#12]
Instead of scraping 2 or 3 lines of lyrics, the CLI argument `-fs` or `--fullsong` should get the whole song lyrics.

**Notes**:
- When this CLI argument is chosen, you must set the `-nt/--notwitter` to `true`.
- If the user didn't write `-nt` with `-fs`, then execute `-fs` and print this below/above the lyrics: `'Full song lyrics can't be tweeted'`.
- If the user wrote both `-nt` and `-fs`, then just print the full song lyrics.

**Comment by cloneartist** [comment]
Hey, Can I work on this one?

**Comment by MohamedYasser97** [comment]
@cloneartist Sure! You can start by forking my repo and coding the changes in a new branch from `master`. And make sure to satisfy the notes mentioned in the issue description.
