### ISSUE TITLE
Add a Readme file

### ISSUE THREAD

**Issue by MohamedYasser97** [MohamedYasser97/lyricurator#15]
- Add a readme file to explain how the program works with its possible argument combinations.
- Try to make it look good with different markdown styles.
- Also make a section that explains how people should contribute.
- Screenshot examples would be a nice bonus.

**Comment by itzROHIT-coder** [comment]
I can help you in this, could you assign this to me?

**Comment by MohamedYasser97** [comment]
@itzROHIT-coder Sure! 😄
Looking forward to a neat readme file, good luck

**Comment by itzROHIT-coder** [comment]
I created a demo readme, will be writing the doc afterwards...

**Comment by MohamedYasser97** [comment]
Whenever the file is ready add me as a reviewer to your PR or ping me to merge your changes

**Comment by itzROHIT-coder** [comment]
okay
