### ISSUE TITLE
Restructure CLI arguments

### ISSUE THREAD

**Issue by MohamedYasser97** [MohamedYasser97/lyricurator#25]
Currently, it's mandatory to use either one of `-nt` or `-t`. It makes no sense to use one of those when we only want to print something in the terminal and exit like `-la`, `-ls` or the upcoming `-hal` and `-hs`.

It's required to make `-nt` or `-t` only mandatory when used with any arguments except the ones mentioned above.

**Comment by kritika-gupta** [comment]
Hi, I just came across this. Could I pick this up?

**Comment by AsyncDeveloper245** [comment]
Hi @MohamedYasser97 I would like to be assigned this issue as i would love to contribute to the project.
